#!/bin/bash

dir=härjarevisan

if !(( -d "$dir" )) ; then
wget -P härjarevisan https://raw.githubusercontent.com/leonpx/Harjarevisan/master/Gardebylaten.mp3 https://raw.githubusercontent.com/leonpx/Harjarevisan/master/harjarevisan https://raw.githubusercontent.com/leonpx/Harjarevisan/master/harjarevisan.man
fi

mpv härjarevisan/Gardebylaten.mp3 &
man härjarevisan/harjarevisan.man
