#!/bin/bash

wget -P härjarevisan https://raw.githubusercontent.com/leonpx/Harjarevisan/master/Gardebylaten.mp3 https://raw.githubusercontent.com/leonpx/Harjarevisan/master/harjarevisan https://raw.githubusercontent.com/leonpx/Harjarevisan/master/harjarevisan.man
chmod +x härjarevisan/harjarevisan
./härjarevisan/harjarevisan
